# -*- coding: utf-8 -*-
from utils.Regex import Regex

__author__ = 'Rabbi-Tuly'

if __name__=='__main__':
    text = '''<table style="width: 187px;" align="center" background=" border="0" cellpadding="0" cellspacing="0"> <tbody> <tr> <td colspan="2"><img src="http://img.photobucket.com/albums/v402/WGT-32/1.png" /> &nbsp;<a href="http://eshops.mercadolivre.com.br/quackstore/" target="_blank"><img src="http://img.photobucket.com/albums/v402/WGT-32/2.png" border="0" /></a> <img src="http://img.photobucket.com/albums/v402/WGT-32/3.png" /> <table style="width: 100%;" border="0" cellpadding="0" cellspacing="0"> <tbody> <tr> <td style="padding-left: 60px;" background="http://img.photobucket.com/albums/v402/WGT-32/fundo.png"> <p>&nbsp;</p> <p>VocÃª estÃ¡ convidado a juntar-se a um grupo que durante uma semana vai estudar com um dos maiores especialistas em lideranÃ§a dos Estados Unidos. Leonard Hoffman, um famoso empresÃ¡rio que abandonou sua brilhante carreira para se tornar monge em um mosteiro beneditino, Ã© o personagem central desta envolvente histÃ³ria criada por James C. Hunter para ensinar de forma clara e agradÃ¡vel os princÃ­pios fundamentais dos verdadeiros lÃ­deres. Se vocÃª tem dificuldade em fazer com que sua equipe dÃª o melhor de si no trabalho e gostaria de se relacionar melhor com sua famÃ­lia e seus amigos, vai encontrar neste livro personagens, idÃ©ias e discussÃµes que vÃ£o abrir um novo horizonte em sua forma de lidar com os outros. Ã‰ impossÃ­vel ler este livro sem sair transformado. "O Monge e o Executivo" Ã©, sobretudo, uma liÃ§Ã£o sobre como se tornar uma pessoa melhor.<br /> <br /> <b>I.S.B.N.: </b>8575421026<br /> <br /> <b>CÃ³d. Barras: </b>9788575421024<br /> <br /> <b>Reduzido: </b>149181<br /> <br /> <b>Altura: </b>21 cm.<br /><b>Largura: </b>14 cm.<br /><b>Acabamento : </b>Brochura<br /><b>EdiÃ§Ã£o : </b>1 / 2004<br /><b>Idioma : </b>PortuguÃªs<br /><b>PaÃ­s de Origem : </b>Brasil<br /><b>NÃºmero de Paginas : </b>144<br /> <br /></p> <p>&nbsp;</p> <p style="text-align: center;"></p> </td> </tr> </tbody> </table> <img src="http://img.photobucket.com/albums/v402/WGT-32/5.png" /><br /> <img src="http://img.photobucket.com/albums/v402/WGT-32/6.png" /><br /> <img src="http://img.photobucket.com/albums/v402/WGT-32/7.png" /><br /> <img src="http://img.photobucket.com/albums/v402/WGT-32/8_usa_pf.png" /><br /> <img src="http://img.photobucket.com/albums/v402/WGT-32/10.png" /><br /> <img src="http://img.photobucket.com/albums/v402/WGT-32/11.png" /></td> </tr> <tr> <td valign="top" width="186"></td> <td valign="top" width="1"></td> </tr> <tr> <td colspan="2"></td> </tr> </tbody> </table>'''
    regex = Regex()
    d = regex.replaceData(r'(?i)(?:<br\s*/>\s*)+', '<br />', text)
    print d